# Generated by Django 3.1 on 2020-09-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200912_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_features',
            field=models.BooleanField(default=False),
        ),
    ]
