# Generated by Django 3.1 on 2020-09-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_is_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_features',
            new_name='is_featured',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
